jobs: 100
#keep-going: True
restart-times: 0
rerun-incomplete: True
use-singularity: True
max-jobs-per-second: 100
resources: load=100
max-status-checks-per-second: 100
snakefile: "/proj/ngi2024001/nobackup/wp2_hg/fluffy/fluffy_new_sample_order/fluffy/workflow/Snakefile"
singularity-args: "-e --cleanenv -B /proj -B $HOME --nv"
singularity-prefix: "/proj/ngi2024001/nobackup/wp2_hg/fluffy/singularity_cache/"
wrapper-prefix: "git+file://proj/ngi2024001/nobackup/wp2_hg/fluffy/fluffy_new_sample_order/snakemake-wrappers/"
drmaa: " -A ngi2024001 -N 1-1 -t {resources.time} -n {resources.threads} --mem={resources.mem_mb} --mem-per-cpu={resources.mem_per_cpu} --mem-per-cpu={resources.mem_per_cpu} --partition={resources.partition} -J {rule} {resources.gres} -e slurm_out/{rule}_%j.err -o slurm_out/{rule}_%j.out"
default-resources: [gres=""]
drmaa-log-dir: "slurm_out"
