jobs: 200
keep-going: True
restart-times: 1
rerun-incomplete: True
use-singularity: True
max-jobs-per-second: 10
resources: load=100
max-status-checks-per-second: 10
use-singularity: True

slurm: True
default-resources:
  - slurm_partition="core"
  - slurm_account="ngi2024001"
  - runtime="12h"
  - nodes=1

set-resources:
  - parabricks_pbrun_fq2bam_recal:slurm_extra="--gres=gpu:l40s:6"
  - parabricks_pbrun_fq2bam_recal:slurm_partition="gpu"
  - parabricks_pbrun_mutectcaller_t:slurm_extra="--gres=gpu:l40s:2"
  - parabricks_pbrun_mutectcaller_t:slurm_partition="gpu"
  - parabricks_pbrun_mutectcaller_tn:slurm_extra="--gres=gpu:l40s:2"
  - parabricks_pbrun_mutectcaller_tn:slurm_partition="gpu"
  - compression_crumble:runtime=2000
  - fusions_fusioncatcher:runtime=2000
  - bbduk:runtime=60

configfiles: ["config/config.yaml", "config/config_production_pipeline.miarka.yaml"]
singularity-args: "-e --cleanenv -B /proj -B $HOME --nv"
singularity-prefix: "/proj/ngi2024001/nobackup/bin/wp2_iht/apptainer_cache"
wrapper-prefix: "git+file://proj/ngi2024001/nobackup/bin/wp2_iht/${TAG_OR_BRANCH}/snakemake-wrappers/"
