decimalPoint_format: ','
extra_fn_clean_exts: ##from this until end
    - '.duplication_metrics'
    - type: regex
      pattern: '^IHT[0-9]+-WP2_'
    - type: regex
      pattern: "_fastq[12]"

table_sample_merge:
  "R1": "_R1_001"
  "R2": "_R2_001"
  "L008": # to remove SX_L00X from ending to enable grouping 
    - type: "regex"
      pattern: "S[0-9]{1,2}_L008"

report_header_info:
  - Contact E-mail: "igp-klinsek-bioinfo@lists.uu.se"
  - Application Type: "Whole Transcriptome Sequencing"
  - Project Type: "WTS"

sp:
  rna_number_table:
    fn: "*RNA_number.table.tsv"

custom_data:
  rna_number_table:
    file_format: "tsv"
    section_name: "RNA number"
    description: "File for connecting Pedegree ID with RNA number in general stats"
    plot_type: "generalstats"
    pconfig:
      - rna_number:
          title: "RNA number"
          description: "RNA number based on SampleSheet"
          placement: 300

# mosdepth custom thresholds
mosdepth_config:
  general_stats_coverage:
    - 1
    - 5
    - 10
    - 15
    - 20
    - 30
    - 50

# Remove suffix from General stats columns
custom_table_header_config:
  general_stats_table:
    reads_properly_paired_percent:
      suffix: ""
    median_coverage:
      title: "Median Coverage"
      suffix: ""
    10_x_pc:
      suffix: ""
    30_x_pc:
      suffix: ""
    50_x_pc:
      suffix: ""
    PERCENT_DUPLICATION:
      suffix: ""
    summed_mean:
      suffix: ""
    PCT_SELECTED_BASES:
      suffix: ""
    ZERO_CVG_TARGETS_PCT:
      suffix: ""
    star-total_reads:
      suffix: ""
      title: "Total readpairs [M]"
    star-mapped_percent:
      suffix: ""
      title: "Aligned [%]"
    star-uniquely_mapped_percent:
      suffix: ""
      title: "Uniq aligned [%]"
    star-multimapped:
      suffix: ""
      title: "Multimapped [M]"
    sortmerna-rRNA_pct:
      suffix: ""
      title: "rRNA [%]"

# General stats column visibility
table_columns_visible:
  FastQC:
    percent_duplicates: False
    percent_gc: False
    avg_sequence_length: False
    percent_fails: False
    total_sequences: False
  fastp:
    pct_adapter: False
    pct_surviving: False
    after_filtering_gc_content: False
    filtering_result_passed_filter_reads: False
    after_filtering_q30_bases: False
    after_filtering_q30_rate: False
    pct_duplication: False
  mosdepth:
    median_coverage: True
    mean_coverage: False
    1_x_pc: False
    5_x_pc: False
    10_x_pc: True
    20_x_pc: False
    30_x_pc: False
    50_x_pc: False
  STAR:
    star-total_reads: True
    star-mapped: False
    star-mapped_percent: True
    star-uniquely_mapped: False
    star-uniquely_mapped_percent: True
    star-multimapped: True
  SortMeRNA:
    rRNA_pct: True
  # Picard:
  #   PCT_PF_READS_ALIGNED: True
  "Picard: Mark Duplicates":
    PERCENT_DUPLICATION: True


# multiqc_cgs:
#   "Picard: Alignment Summary":
#     MEAN_READ_LENGTH:
#       title: "Mean Read Length"
#       description: "Mean read length from Picard Alignment Summary Metrics"
#       format: "{:.1f}"