decimalPoint_format: ','
extra_fn_clean_exts: ##from this until end
    - '.duplication_metrics'
    - type: regex
      pattern: '^HG[0-9]+-[A-Za-z0-9-]+_'
    - type: regex
      pattern: '_fastq[12]'

table_sample_merge:
  "R1": "_R1_001"
  "R2": "_R2_001"
  "L008": # to remove SX_L00X from ending to enable grouping 
    - type: "regex"
      pattern: "_S[0-9]{1,2}_L008"
  "L007": # to remove SX_L00X from ending to enable grouping 
    - type: "regex"
      pattern: "_S[0-9]{1,2}_L007"
  "L006": # to remove SX_L00X from ending to enable grouping 
    - type: "regex"
      pattern: "_S[0-9]{1,2}_L006"
  "L005": # to remove SX_L00X from ending to enable grouping 
    - type: "regex"
      pattern: "_[0-9]{1,2}_L005"
  "L004": # to remove SX_L00X from ending to enable grouping 
    - type: "regex"
      pattern: "_S[0-9]{1,2}_L004"
  "L003": # to remove SX_L00X from ending to enable grouping 
    - type: "regex"
      pattern: "_S[0-9]{1,2}_L003"
  "L002": # to remove SX_L00X from ending to enable grouping 
    - type: "regex"
      pattern: "_S[0-9]{1,2}_L002"
  "L001": # to remove SX_L00X from ending to enable grouping 
    - type: "regex"
      pattern: "_S[0-9]{1,2}_L001"

report_header_info:
  - Contact E-mail: "igp-klinsek-bioinfo@lists.uu.se"
  - Application Type: "TrueSeq PCR Free WGS"
  - Project Type: "Whole Genome"

sp:
  dna_number_table:
    fn: "*DNA_number.table.tsv"

custom_data:
  dna_number_table:
    file_format: "tsv"
    section_name: "DNA number"
    description: "File for connecting Pedegree ID with DNA number in general stats"
    plot_type: "generalstats"
    pconfig:
      - dna_number:
          title: "DNA number"
          description: "DNA number based on SampleSheet"

# mosdepth custom thresholds
mosdepth_config:
  general_stats_coverage:
    - 1
    - 5
    - 10
    - 15
    - 20
    - 30
    - 50

# Remove suffix in general stats
custom_table_header_config:
  general_stats_table:
    raw_total_sequences:
      suffix: ""
      title: "Total seqs [M]"
    reads_mapped:
      suffix: ""
      title: "Reads mapped [M]"
    reads_mapped_percent:
      suffix: ""
    reads_properly_paired_percent:
      suffix: ""
    median_coverage:
      suffix: ""
    10_x_pc:
      suffix: ""
    30_x_pc:
      suffix: ""
    50_x_pc:
      suffix: ""
    PERCENT_DUPLICATION:
      suffix: ""
      title: "Duplication [%]"
    summed_mean:
      suffix: ""

# General stats column visibility
table_columns_visible:
  FastQC:
    percent_duplicates: False
    percent_gc: False
    avg_sequence_length: False
    percent_fails: False
    total_sequences: False
  fastp:
    pct_adapter: False
    pct_surviving: False
    after_filtering_gc_content: False
    filtering_result_passed_filter_reads: False
    after_filtering_q30_bases: False
    after_filtering_q30_rate: False
    pct_duplication: False
  mosdepth:
    median_coverage: True
    mean_coverage: False
    1_x_pc: False
    5_x_pc: False
    10_x_pc: True
    20_x_pc: False
    30_x_pc: True
    50_x_pc: True
  "Picard: HsMetrics":
    FOLD_ENRICHMENT: False
    MEDIAN_TARGET_COVERAGE: False
    PCT_TARGET_BASES_30X: False
    ZERO_CVG_TARGETS_PCT: False
  "Picard: InsertSizeMetrics":
    summed_median: False
    summed_mean: True
  "Picard: Mark Duplicates":
    PERCENT_DUPLICATION: True
  "Picard: WgsMetrics":
    MEDIAN_COVERAGE: False
    MEAN_COVERAGE: False
    SD_COVERAGE: False
    PCT_30X: False
  "Samtools: stats":
    error_rate: False
    non-primary_alignments: False
    reads_mapped: False
    reads_mapped_percent: True
    reads_properly_paired_percent: True
    reads_MQ0_percent: False
    raw_total_sequences: True #tidigare from picard

# Custom columns to general stats
multiqc_cgs:
  "Picard: HsMetrics":
    FOLD_80_BASE_PENALTY:
      title: "Fold80"
      description: "Fold80 penalty from picard hs metrics"
      min: 1
      max: 3
      scale: "RdYlGn-rev"
      format: "{:.1f}"
    PCT_SELECTED_BASES:
      title: "Bases on Target"
      description: "On+Near Bait Bases / PF Bases Aligned from Picard HsMetrics"
      format: "{:.2%}"
    ZERO_CVG_TARGETS_PCT:
      title: "Target bases with zero coverage [%]"
      description: "Target bases with zero coverage [%] from Picard"
      min: 0
      max: 100
      scale: "RdYlGn-rev"
      format: "{:.2%}"
  "Samtools: stats":
    average_quality:
      title: "Average Quality"
      description: "Ratio between the sum of base qualities and total length from Samtools stats"
      min: 0
      max: 60
      scale: "RdYlGn"

# Galler alla kolumner oberoende pa module!
table_columns_placement:
  "Custom content: dna_number_table":
    dna_number: 300
  mosdepth:
    median_coverage: 601
    1_x_pc: 666
    5_x_pc: 666
    10_x_pc: 602
    15_x_pc: 603
    20_x_pc: 604
    30_x_pc: 605
    50_x_pc: 606
  "Samtools: stats":
    raw_total_sequences: 500
    reads_mapped: 501
    reads_mapped_percent: 502
    reads_properly_paired_percent: 503
    average_quality: 504
    error_rate: 555
    reads_MQ0_percent: 555
    non-primary_alignments: 555
  "Picard: HsMetrics":
    FOLD_ENRICHMENT: 888
    MEDIAN_TARGET_COVERAGE: 888
    PCT_TARGET_BASES_30X: 888
    FOLD_80_BASE_PENALTY: 801
    PCT_SELECTED_BASES: 800
    ZERO_CVG_TARGETS_PCT: 805
  "Picard: InsertSizeMetrics":
    summed_median: 803
    summed_mean: 803
  "Picard: Mark Duplicates":
    PERCENT_DUPLICATION: 802
