somalier_sex_check:
  parent_id: somalier_section
  parent_name: "Somalier"
  parent_description: "This parent section contains one or more sub-sections below it"
  id: 'somalier_sex_check_table'
  format: tsv
  plot_type: 'table'
  section_name: 'Sex check'
  description: 'Check on the sex of a sample with Somalier'
  pconfig:
       namespace: 'Cust Data3'
  headers:
    inferred_sex:
      title: inferred sex
      description: inferred sex from .bam file
    reported_sex:
      title: reported sex
      description: sex from pedigree file
    sex_check:
      title: sex check
      description: Pass when inferred sex and reported sex agree.
