# Miarka site config for fluffy_hematology_wgs
REFERENCE_DATA: "/proj/ngi2024001/nobackup/bin/wp2_iht/design_and_ref_files"
APPTAINER_CACHE: "/proj/ngi2024001/nobackup/bin/wp2_iht/apptainer_cache"
hydra_local_path: "/proj/ngi2024001/nobackup/bin/wp2_iht/hydra-genetics"

resources: "{{FLUFFY_HOME}}/config/resources/resources_miarka.yaml"

CONTAINER_PREFIX: "{{APPTAINER_CACHE}}"
CONTAINER_SUFFIX: "_"
CONTAINER_EXT: ".sif"

HYDRAGENETICS_PREFIX: "{{APPTAINER_CACHE}}"
NVIDIA_PREFIX: "{{APPTAINER_CACHE}}"
BRENTP_PREFIX: "{{APPTAINER_CACHE}}"
TRINITYCTAT_PREFIX: "{{APPTAINER_CACHE}}"
KINCEKARA_PREFIX: "{{APPTAINER_CACHE}}"

# Miarka Reference File Paths
ref_design_bed: "{{REFERENCE_DATA}}/fluffy/homo_sapiens.hg38.wgs.bed"
ref_design_intervals: "{{REFERENCE_DATA}}/fluffy/Twist_Comprehensive_Exome_Covered_Targets_hg38.interval_list"
ref_design_intervals_gatk_cnv: "{{REFERENCE_DATA}}/fluffy/gatk/hg38.preprocessed.20250926.interval_list"
ref_fasta: "{{REFERENCE_DATA}}/fluffy/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta"
ref_fasta_rna: "{{REFERENCE_DATA}}/fluffy/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
ref_fai: "{{REFERENCE_DATA}}/fluffy/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.fai"
ref_dict: "{{REFERENCE_DATA}}/fluffy/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.dict"
ref_genome_dir: "{{REFERENCE_DATA}}/fluffy/homo_sapiens_star/"
ref_sites: "{{REFERENCE_DATA}}/fluffy/Homo_sapiens_assembly38.known_indels.vcf.gz"
ref_simple_repeats: ""
ref_wgs_intervals: "{{REFERENCE_DATA}}/fluffy/homo_sapiens.hg38.wgs.interval_list"
ref_target_genes: ""
ref_cna_exons: "{{REFERENCE_DATA}}/fluffy/hg38_CNA.bed"
ref_arriba_assembly: "{{REFERENCE_DATA}}/fluffy/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
ref_arriba_blacklist: "{{REFERENCE_DATA}}/fluffy/blacklist_hg38_GRCh38_v2.5.1.tsv.gz"
ref_arriba_extra: "-p {{REFERENCE_DATA}}/fluffy/protein_domains_hg38_GRCh38_v2.5.1.gff3 -k {{REFERENCE_DATA}}/fluffy/known_fusions_hg38_GRCh38_v2.5.1.tsv.gz"
ref_arriba_gtf: "{{REFERENCE_DATA}}/fluffy/Homo_sapiens.GRCh38.115.chr.gtf"
ref_arriba_draw_cytobands: "{{REFERENCE_DATA}}/fluffy/cytobands_hg38_GRCh38_v2.5.1.tsv"
ref_arriba_draw_gtf: "{{REFERENCE_DATA}}/fluffy/Homo_sapiens.GRCh38.115.chr.gtf"
ref_arriba_draw_protein_domains: "{{REFERENCE_DATA}}/fluffy/protein_domains_hg38_GRCh38_v2.5.1.gff3"
ref_bcftools_snv_all: "{{REFERENCE_DATA}}/fluffy/all_snv_38.bed"
ref_bcftools_snv_aml: "{{REFERENCE_DATA}}/fluffy/aml_snv_38_2022-02-25.bed"
ref_bcftools_snv_tm: "{{REFERENCE_DATA}}/fluffy/Twist_myeloid_coding_exons_added_regions.250904.bed"
ref_bcftools_sv_all: "{{REFERENCE_DATA}}/fluffy/all_sv_38.bed"
ref_bcftools_sv_aml: "{{REFERENCE_DATA}}/fluffy/aml_sv_38.bed"
ref_cnvkit_pon: "{{REFERENCE_DATA}}/fluffy/cnvkit/Reference_Normal_pool.WGS.250822.bin1000.cnn"
ref_cnvkit_table_bed: "{{REFERENCE_DATA}}/fluffy/cnvkit/hg38_CNA.bed"
ref_cnvkit_table_cyto: "{{REFERENCE_DATA}}/fluffy/cnvkit/genomicPos_cytogenCoord.txt"
ref_fusioncatcher_path: "{{REFERENCE_DATA}}/fluffy/fusioncatcher/human_v102"
ref_gatk_snp_interval: "{{REFERENCE_DATA}}/fluffy/gnomad.genomes.r3.0.sites.maf001.snv-only.hg38.sorted.vcf"
ref_gatk_pon_female: "{{REFERENCE_DATA}}/fluffy/gatk_pon/gatk_cnv_panel_of_normal_female.20250926.hdf5"
ref_gatk_pon_male: "{{REFERENCE_DATA}}/fluffy/gatk_pon/gatk_cnv_panel_of_normal_male.20250926.hdf5"
ref_merge_cnv_ref_genes: "{{REFERENCE_DATA}}/fluffy/cnv_report/refGene_hg38.txt"
ref_mosdepth_design_bed: "{{REFERENCE_DATA}}/fluffy/GRCh38_all_exon_sorted.bed"
ref_pindel_include_bed: "{{REFERENCE_DATA}}/fluffy/pindel/aml_pindel_38_240912.bed"
ref_rseqc_gene_body_bed: "{{REFERENCE_DATA}}/fluffy/hg38_GENCODE_V38.downsampled.bed"
ref_rseqc_inner_dist_bed: "{{REFERENCE_DATA}}/fluffy/hg38_GENCODE.v38.bed"
ref_simple_sv_panel: "{{REFERENCE_DATA}}/fluffy/az-cancer-panel.txt"
ref_simple_sv_fusion_pairs: "{{REFERENCE_DATA}}/fluffy/fusion_pairs.txt"
ref_snpeff_db: "{{REFERENCE_DATA}}/fluffy/snpeff/GRCh38.99"
ref_somalier_sites: "{{REFERENCE_DATA}}/fluffy/somalier/sites.hg38.vcf.gz"
ref_sortmerna_fasta1: "{{REFERENCE_DATA}}/fluffy/sortmerna/sortmerna/rfam-5.8s-database-id98.fasta"
ref_sortmerna_fasta2: "{{REFERENCE_DATA}}/fluffy/sortmerna/sortmerna/rfam-5s-database-id98.fasta"
ref_sortmerna_fasta3: "{{REFERENCE_DATA}}/fluffy/sortmerna/sortmerna/silva-bac-16s-id90.fasta"
ref_sortmerna_fasta4: "{{REFERENCE_DATA}}/fluffy/sortmerna/sortmerna/silva-bac-23s-id98.fasta"
ref_sortmerna_fasta5: "{{REFERENCE_DATA}}/fluffy/sortmerna/sortmerna/silva-euk-18s-id95.fasta"
ref_sortmerna_fasta6: "{{REFERENCE_DATA}}/fluffy/sortmerna/sortmerna/silva-euk-28s-id98.fasta"
ref_sortmerna_index: "{{REFERENCE_DATA}}/fluffy/sortmerna/sortmerna/idx"
ref_star_index: "{{REFERENCE_DATA}}/fluffy/star_arriba/Homo_sapiens.GRCh38.dna.115.star_reference"
ref_star_fusion_path: "{{REFERENCE_DATA}}/fluffy/star-fusion/GRCh38_gencode_v37_CTAT_lib_Mar012021.plug-n-play/ctat_genome_lib_build_dir"
ref_svdb_query_db: "{{REFERENCE_DATA}}/fluffy/230601_svdb_cnv.vcf"
ref_svdb_query_db_manta: ""
ref_vep_cache: "{{REFERENCE_DATA}}/fluffy/vep/"
