name: Lint

on:
  push:
    branches:
     - develop
     - main
  pull_request:
    branches:
     - develop
     - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Linting
        working-directory: .tests/integration
        run: |
          snakemake --lint -n -s ../../workflow/Snakefile --configfiles ../../config/config.yaml config.yaml --config FLUFFY_HOME=../..
